### ISSUE TITLE
Make page wider?

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/blog.piston.rs#31]
http://blog.piston.rs/2014/08/29/inside-the-game-loop/

The code wraps to a new line.

@mitchmindtree suggested to make code blocks scrollable.

@eddyb suggest to make the page wider.

**Comment by indiv0** [comment]
As a side note, the current highlight colors and font make the code quite hard to read, I'll look into changing that.

As for scrollability/widening, I can implement either, but I'm not sure which would be best.

**Comment by mitchmindtree** [comment]
http://i.imgur.com/SxprH.gif

**Comment by indiv0** [comment]
@mitchmindtree well personally I'd only rather have scrollable code blocks, because the site already fits nicely to accomodate viewport size.

Additionally, it's typically considered bad practice in web design to make the website too wide, as it decreases readability.

I think simply implementing scrollable code blocks is best as it lets the code take up as much space as it needs, without affecting text; additionally, scrollbars disappear if the screen can fit the entire code block, which also looks nice.

**Comment by mitchmindtree** [comment]
Yeah agreed with this @Indiv0 the scrolling will look nice :+1:
